import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { ConnectButton } from '@rainbow-me/rainbowkit';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-900 text-white">
        <nav className="bg-gray-800 py-6 px-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-3xl font-bold">ZNS Admin Dashboard</h1>
            <button className="bg-blue-500 text-white px-4 py-2 rounded-2xl">
              Connect Wallet
            </button>
          </div>
        </nav>
        <main className="container mx-auto p-10">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
